os:
  - osx
osx_image: xcode8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
#  - ./flutter/bin/flutter doctor
#  - export IOS_SIMULATOR_UDID=$(instruments -s devices | grep "iPhone 5s (10.1)" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')   # Get the iPhone 5s deviceid
#  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID  # Launch the iOS Simulator
#  - sleep 180  # Wait 120 seconds
#  - xcrun simctl list | grep "(Booted)"    # Just checking to see the right device is marked as booted....seems OK
#  - travis_retry xcrun simctl openurl booted http://travis-ci.com  # Open a URL
script:
  - xcrun simctl list
#  - ./flutter/bin/flutter drive test_driver/simple.dart
cache:
  directories:
    - $HOME/.pub-cache



#os: linux
#language: android
#licenses:
#  - 'android-sdk-preview-license-.+'
#  - 'android-sdk-license-.+'
#  - 'google-gdk-license-.+'
#android:
#  components:
#    - tools
#    - platform-tools
#    - build-tools-26.0.2
#    - android-27
#    - android-25
#    - android-22
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - sys-img-armeabi-v7a-android-22
#jdk: oraclejdk8
#sudo: false
#addons:
#  apt:
#    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
#    sources:
#      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
#    packages:
#      - libstdc++6
#      - fonts-droid
## https://stackoverflow.com/questions/47719282/i-cant-build-android-27-tool-27-0-2-with-travis-ci/47726910#47726910
#before_install:
#  - yes | sdkmanager "platforms;android-27"
#before_script:
#  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
#  - unzip -qq gradle-3.5-bin.zip
#  - export GRADLE_HOME=$PWD/gradle-3.5
#  - export PATH=$GRADLE_HOME/bin:$PATH
#  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
#  - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
#  - ./flutter/bin/flutter doctor
#script:
#  #- ./flutter/bin/flutter test
#  #- ./flutter/bin/flutter drive ./test_driver/simple.dart
#  - ./flutter/bin/flutter -v build apk
#
#cache:
#  directories:
#    - $HOME/.pub-cache